[package]
name = "cargo-warehouse"
description = "A simple cargo script for set up a local cache for compiled dependencies"
license = "MIT"
version = "1.0.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
junction = "1.2.0"
sudo = "0.6.0"
windows-elevate = "0.1.0"
